service: d-from-sqs-to-firehose

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "firehose:*"
      Resource: 
        - "arn:aws:firehose:us-west-2:007774094020:deliverystream/firehose-ds"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: 
        - "arn:aws:s3:::*"

functions:
  myEventTrigger:
    handler: handler.step04
    events:
      - sqs:
          arn: arn:aws:sqs:us-west-2:007774094020:second-queue
          batchSize: 1
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures
