name: 'Serverless - Deploy'

on:
  push:
    branches:
    - main
    paths: 
    - event_oriented_pipeline/**
  pull_request:
    branches:
    - main
    paths: 
    - event_oriented_pipeline/**

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: staging 
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install deploy compose
      run: npm i serverless-compose
      with:
        node-version: ${{ matrix.node-version }}

    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: -c "cd ./event_oriented_pipeline && serverless deploy"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}